version : '3.4'
services:
  mysql:
    build:
      context: ./
      dockerfile: mysql.dockerfile
    logging:
      driver: none
    networks:
      - network1
  admin:
    build:
      context: ./
      dockerfile: admin-tomcat.dockerfile
    ports:
      - "8080:8080"
    networks:
      - network1
    depends_on:
      - mysql
    entrypoint: bash -c "sleep 7s && catalina.sh run"

networks:
  network1:
    driver: bridge